#!/usr/bin/env python3
"""Figure 3 redrawn from the archived notebook result files (data/archived_runs/).

These are the result files of the original runs that produced the published figure
(see data/archived_runs/README.md): Monte Carlo, Truncated Monte Carlo and Kernel SHAP
on the 48 games with seeds 0 to 9, and adaptive Cluster Shapley over the 41 epsilon
values. The plotting code follows the research notebook
(Shapley_Value_Baselines_Appendix.ipynb): the runs of each sampling method are pooled over
seeds, games and budgets and grouped by the exact number of unique subsets evaluated; the
curve is the mean MAE of each group and the band its 95% t interval. The Cluster Shapley
curve is the mean over the 48 games at each epsilon.

Outputs (outputs/main_text/):
  figure3_from_archived_runs.pdf and .png
  figure3_from_archived_runs_points.csv    every plotted point

figure3_benchmark_comparison.py draws the same figure from the runs regenerated by this
package; the two agree to within sampling error.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from scipy import stats  # noqa: E402

PACKAGE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PACKAGE / "code" / "algorithms"))
from run_baselines import write_csv  # noqa: E402

ARCHIVE = PACKAGE / "data" / "archived_runs"
BASELINES = {
    "tmc": ("Truncated Monte Carlo", "blue", "--",
            ARCHIVE / "figure3_baselines" / "truncated_monte_carlo" / "tmc_0.5_detailed_results_{}_mape_0.1.csv"),
    "mc": ("Monte Carlo", "red", ":",
           ARCHIVE / "figure3_baselines" / "monte_carlo" / "permutation_detailed_results_{}_mape_0.1.csv"),
    "kernel": ("Kernel SHAP", "purple", "-.",
               ARCHIVE / "figure3_baselines" / "kernel_shap" / "kernel_shap_detailed_results_{}_mape_0.1.csv"),
}
CLUSTER_FILE = ARCHIVE / "figure3_cluster" / "clustering_results_with_step.csv"
LABELLED_EPSILONS = (0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2)


def pooled_curve(files):
    runs = pd.concat([pd.read_csv(f).assign(seed=i) for i, f in enumerate(files)], ignore_index=True)
    grouped = runs.groupby("unique_subsets")["mae"].agg(["mean", "std", "count"]).reset_index()
    dof = np.maximum(grouped["count"] - 1, 1)
    half = np.where(grouped["count"] > 1,
                    stats.t.ppf(0.975, dof) * grouped["std"].fillna(0.0) / np.sqrt(grouped["count"]), 0.0)
    return grouped["unique_subsets"].to_numpy(float), grouped["mean"].to_numpy(), half, grouped["count"].to_numpy()


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seeds", type=int, default=10, help="number of archived seeds per method")
    parser.add_argument("--output-dir", type=Path, default=PACKAGE / "outputs/main_text")
    parser.add_argument("--xlim", type=float, nargs=2, default=(20, 180))
    parser.add_argument("--ylim", type=float, nargs=2, default=(0, 1))
    args = parser.parse_args()

    fig, ax = plt.subplots(figsize=(10, 6.6))
    points = []
    for key, (label, color, style, pattern) in BASELINES.items():
        files = [Path(str(pattern).format(i)) for i in range(args.seeds)]
        missing = [f for f in files if not f.exists()]
        if missing:
            raise SystemExit(f"Missing archived result file: {missing[0]}")
        x, y, half, n = pooled_curve(files)
        ax.plot(x, y, color=color, linestyle=style, linewidth=2, label=label)
        ax.fill_between(x, y - half, y + half, color=color, alpha=0.2, linewidth=0)
        points += [{"method": label, "epsilon": "", "unique_subsets": float(xi), "mae": float(yi),
                    "ci95_halfwidth": float(hi), "runs_in_group": int(ni)}
                   for xi, yi, hi, ni in zip(x, y, half, n)]

    cluster = pd.read_csv(CLUSTER_FILE)
    means = cluster.groupby("iterations")[["mae", "unique_subsets"]].mean().reset_index()
    means = means.rename(columns={"iterations": "epsilon"}).sort_values("unique_subsets")
    ax.plot(means["unique_subsets"], means["mae"], color="green", linestyle="-", linewidth=2,
            label="Cluster Shapley")
    for _, row in means.iterrows():
        points.append({"method": "Cluster Shapley", "epsilon": float(row["epsilon"]),
                       "unique_subsets": float(row["unique_subsets"]), "mae": float(row["mae"]),
                       "ci95_halfwidth": 0.0, "runs_in_group": int(cluster["dataset_id"].nunique())})
        if any(abs(row["epsilon"] - e) < 1e-9 for e in LABELLED_EPSILONS):
            ax.plot(row["unique_subsets"], row["mae"], "o", color="green", markersize=6)
            ax.annotate(f"$\\epsilon$={row['epsilon']:g}", (row["unique_subsets"], row["mae"]),
                        textcoords="offset points", xytext=(4, -15), fontsize=11, rotation=-15)

    ax.set_xlim(*args.xlim)
    ax.set_ylim(*args.ylim)
    ax.set_xlabel("Mean Number of Unique Subsets", fontsize=14)
    ax.set_ylabel("Mean MAE", fontsize=14)
    ax.tick_params(labelsize=12)
    ax.grid(alpha=0.3)
    order = [("Cluster Shapley", "green", "-")] + [(v[0], v[1], v[2]) for v in BASELINES.values()]
    handles = [plt.Line2D([], [], color=c, linestyle=s, linewidth=2, label=l) for l, c, s in order]
    ax.legend(handles=handles, fontsize=13, frameon=True)

    out = args.output_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    fig.savefig(out / "figure3_from_archived_runs.pdf", bbox_inches="tight")
    fig.savefig(out / "figure3_from_archived_runs.png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    write_csv(out / "figure3_from_archived_runs_points.csv", points)
    labelled = means[means["epsilon"].round(3).isin(LABELLED_EPSILONS)]
    print("Cluster Shapley curve from the archived run (epsilon, mean unique subsets, mean MAE):")
    for _, row in labelled.sort_values("epsilon", ascending=False).iterrows():
        print(f"  {row['epsilon']:.2f}  {row['unique_subsets']:8.3f}  {row['mae']:.4f}")
    print(f"Wrote {out / 'figure3_from_archived_runs.pdf'} with {len(points)} plotted points")


if __name__ == "__main__":
    main()
