#!/usr/bin/env python3
"""Main-text table `tab:accuracy_efficiency`: simple attribution rules (Panel A) and
Cluster Shapley under varying epsilon (Panel B).

Inputs, all offline:
  data/coalition_games_8doc/*.csv
      The 48 archived coalition games: averaged coalition scores and the stored
      document values ("Comment i" rows).
  outputs/algorithms/cluster/cluster_summary.csv
      Written by code/algorithms/run_cluster.py: adaptive clustering (method
      "separated") on the archived text-embedding-3-large singleton-summary
      embeddings over the default 41-value epsilon grid.
  data/embeddings/main_8doc_retrieval/retrieval_embedding_manifest.json
      text-embedding-3-large vectors of the eight retrieved review strings and the
      query of every game (collected 2026-09-06). The relevance-weighted rule uses
      s_i(q) = cosine_similarity(e_i, e_q), w_i = s_i / sum_j s_j and
      phi_i = v(q, A(q, S_q)) * w_i.

Outputs (outputs/main_text/):
  table2_panel_a.csv and .tex                simple rules: MAE, MSE and cost
  table2_panel_b.csv and .tex                Cluster Shapley: MAE, MSE, MAPE and cost
  table2_accuracy_efficiency.tex             both panels with separate column headings
  relevance_weights_by_document.csv         similarities, weights and values per document

Each CSV reports both the stored and recomputed-exact targets. TeX tables use
the stored-value target. The former combined table2_accuracy_efficiency.csv is
removed from the output directory because the panels have different metric columns.

Use --panel-a-only to calculate the simple rules directly from the saved games and
retrieval embeddings, without running Cluster Shapley first. This writes
only table2_panel_a.csv, table2_panel_a.tex and relevance_weights_by_document.csv.
It also removes a previous combined table2_accuracy_efficiency.tex from that directory.

MAE and MSE are averaged over documents within a game and then over the 48 games.
Panel A does not calculate MAPE. Panel B retains the cluster run's stabilized
MAPE denominator (true value + 0.1). Computation cost is the number of unique
coalitions evaluated divided by 255.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys

import numpy as np

PACKAGE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PACKAGE / "code" / "algorithms"))
from run_baselines import exact_shapley, load_game, write_csv  # noqa: E402

PANEL_B_EPSILONS = [0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.01]
TARGETS = ["stored", "recomputed_exact"]


def read_rows(path):
    with Path(path).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def relevance_scores(manifest_path, name):
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    if manifest.get("model") != "text-embedding-3-large":
        raise ValueError("Retrieval embeddings must come from text-embedding-3-large")
    files = manifest["files"][name]
    reviews = np.load(Path(manifest_path).parent / files["reviews"], allow_pickle=False)
    query = np.load(Path(manifest_path).parent / files["query"], allow_pickle=False)
    similarities = reviews @ query / (np.linalg.norm(reviews, axis=1) * np.linalg.norm(query))
    if np.any(similarities <= 0):
        raise ValueError(f"{name}: nonpositive relevance score; relevance weights require positive scores")
    return similarities


def allocation_errors(target, estimate):
    error = target - estimate
    return {"mae": float(np.mean(np.abs(error))), "mse": float(np.mean(error ** 2))}


def mean_errors(records):
    return {key: float(np.mean([r[key] for r in records])) for key in ["mae", "mse"]}


def panel_tex(rows, panel):
    stored = [r for r in rows if r["target"] == "stored"]
    lines = ["% Regenerated by code/main_text/table2_accuracy_efficiency.py (stored-value target)."]
    if panel == "A":
        lines += ["\\begin{tabular}{lccc}", "\\toprule",
                  "\\multicolumn{4}{c}{\\textbf{Panel A: Simple attribution rules}} \\\\",
                  "\\midrule",
                  "\\textbf{Method} & \\textbf{MAE} & \\textbf{MSE} & \\textbf{Computation Cost} \\\\",
                  "\\midrule"]
        for r in stored:
            lines.append(f"{r['method']} & {r['mae']:.4f} & {r['mse']:.4f} & {r['cost']:.2f} \\\\")
    else:
        lines += ["\\begin{tabular}{ccccc}", "\\toprule",
                  "\\multicolumn{5}{c}{\\textbf{Panel B: Cluster Shapley}} \\\\",
                  "\\midrule",
                  "\\textbf{$\\epsilon$} & \\textbf{MAE} & \\textbf{MSE} & \\textbf{MAPE} & \\textbf{Computation Cost} \\\\",
                  "\\midrule"]
        for r in stored:
            lines.append(f"{r['epsilon']:.2f} & {r['mae']:.4f} & {r['mse']:.4f} & "
                         f"{r['mape']:.2f}\\% & {r['cost']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", type=Path, default=PACKAGE / "data/coalition_games_8doc")
    parser.add_argument("--cluster-summary", type=Path,
                        default=PACKAGE / "outputs/algorithms/cluster/cluster_summary.csv")
    parser.add_argument("--retrieval-manifest", type=Path,
                        default=PACKAGE / "data/embeddings/main_8doc_retrieval/retrieval_embedding_manifest.json")
    parser.add_argument("--output-dir", type=Path, default=PACKAGE / "outputs/main_text")
    parser.add_argument("--panel-a-only", action="store_true",
                        help="Compute Panel A from saved inputs; no cluster-summary file required")
    args = parser.parse_args()

    paths = sorted(args.data_dir.resolve().glob("*.csv"))
    if not paths:
        raise SystemExit("No archived games found")
    per_game = {t: {"Equal Attribution": [], "Relevance-Weighted": []} for t in TARGETS}
    relevance_rows = []
    for path in paths:
        values, stored = load_game(path)
        exact = exact_shapley(values)
        n = len(stored)
        full = values[-1]
        equal = np.full(n, full / n)
        similarities = relevance_scores(args.retrieval_manifest, path.name)
        weights = similarities / similarities.sum()
        relevance = full * weights
        for i in range(n):
            relevance_rows.append({"dataset": path.name, "document": i,
                                   "cosine_similarity": float(similarities[i]),
                                   "weight": float(weights[i]),
                                   "relevance_weighted_value": float(relevance[i]),
                                   "equal_value": float(equal[i]),
                                   "stored_value": float(stored[i]),
                                   "recomputed_exact_value": float(exact[i])})
        for name, target in [("stored", stored), ("recomputed_exact", exact)]:
            per_game[name]["Equal Attribution"].append(allocation_errors(target, equal))
            per_game[name]["Relevance-Weighted"].append(allocation_errors(target, relevance))

    panel_a = []
    for name in TARGETS:
        panel_a.append({"panel": "A", "method": "Exact Shapley", "target": name,
                        "mae": 0.0, "mse": 0.0, "cost": 1.0, "query_runs": len(paths)})
        for method in ["Equal Attribution", "Relevance-Weighted"]:
            panel_a.append({"panel": "A", "method": method, "target": name,
                            **mean_errors(per_game[name][method]), "cost": 0.0,
                            "query_runs": len(per_game[name][method])})
    panel_b = []
    if not args.panel_a_only:
        cluster = read_rows(args.cluster_summary)
        for name in TARGETS:
            for epsilon in PANEL_B_EPSILONS:
                match = [r for r in cluster if r["method"] == "separated" and r["target"] == name
                         and abs(float(r["initial_epsilon"]) - epsilon) < 1e-9]
                if len(match) != 1:
                    raise SystemExit(f"cluster summary lacks epsilon {epsilon} for target {name}; "
                                     "run code/algorithms/run_cluster.py with its default 41-value grid")
                r = match[0]
                panel_b.append({"panel": "B", "method": "Cluster Shapley", "epsilon": epsilon, "target": name,
                                "mae": float(r["mae"]), "mse": float(r["mse"]), "mape": float(r["mape"]),
                                "cost": float(r["normalized_cost"]), "query_runs": int(r["query_runs"])})

    out = args.output_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    # These exact filenames belong to this producer. Remove the retired schema
    # and, for an A-only run, the previous combined table to avoid stale A MAPE.
    (out / "table2_accuracy_efficiency.csv").unlink(missing_ok=True)
    if args.panel_a_only:
        (out / "table2_accuracy_efficiency.tex").unlink(missing_ok=True)
    write_csv(out / "table2_panel_a.csv", panel_a)
    write_csv(out / "relevance_weights_by_document.csv", relevance_rows)
    tex_a = panel_tex(panel_a, "A")
    (out / "table2_panel_a.tex").write_text(tex_a, encoding="utf-8")
    if not args.panel_a_only:
        write_csv(out / "table2_panel_b.csv", panel_b)
        tex_b = panel_tex(panel_b, "B")
        (out / "table2_panel_b.tex").write_text(tex_b, encoding="utf-8")
        (out / "table2_accuracy_efficiency.tex").write_text(
            tex_a + "\n\\par\\medskip\n\n" + tex_b, encoding="utf-8")

    print("Panel A: computed attribution errors and costs (stored-value target)")
    print(f"{'row':<22}{'MAE':>10}{'MSE':>10}{'cost':>10}")
    for row in panel_a:
        if row["target"] != "stored":
            continue
        print(f"{row['method']:<22}{row['mae']:10.4f}{row['mse']:10.4f}{row['cost']:10.2f}")
    print(f"Wrote {out / 'table2_panel_a.csv'}")
    if not args.panel_a_only:
        print("Panel B: Cluster Shapley errors and costs (stored-value target)")
        print(f"{'epsilon':<22}{'MAE':>10}{'MSE':>10}{'MAPE':>12}{'cost':>10}")
        for row in panel_b:
            if row["target"] != "stored":
                continue
            print(f"{row['epsilon']:<22.2f}{row['mae']:10.4f}{row['mse']:10.4f}"
                  f"{row['mape']:11.2f}%{row['cost']:10.2f}")
        print(f"Wrote {out / 'table2_panel_b.csv'}")


if __name__ == "__main__":
    main()
